blueprint:
  name: Ring Keypad Automations
  description: Automations to use the Ring Keypad with an Alarm Panel integration.  See https://github.com/ImSorryButWho/HomeAssistantNotes/blob/main/RingKeypadV2.md for more information.
  domain: automation
  input:
    keypad:
      name: Keypad Device
      description: The device entry for the Ring keypad
      selector:
        device:
          manufacturer: Ring
          integration: zwave_js
    alarm:
      name: Alarm Control Panel entity
      description: The Alarm Control Panel to synchronize the keypad with
      selector:
        entity:
          domain: alarm_control_panel
          integration: alarmo
    pincode:
      name: Temporary Variable for Pincode
      description: The pincode has to be temporarily stored to be able to reuse it for bypass validation. You first need to setup a text_input helper in HA and select it here. Set the display mode to password to hide the password.
      selector:
        entity:
            domain: input_text
    selected_action_police:
      name: Selected Action Police
      description: Select the action for Police Button
      default: []
      selector:
        action:
    selected_action_fire:
      name: Selected Action Fire
      description: Select the action for Fire Button
      default: []
      selector:
        action:
    selected_action_medical:
      name: Selected Action Medical
      description: Select the action for Medical Button
      default: []
      selector:
        action:
variables:
  alarm: !input alarm
  _pincode: !input pincode
mode: parallel
max: 10
trigger:
  - platform: event
    event_type: "zwave_js_notification"
    event_data:
      command_class: 111
      device_id: !input keypad
      event_type: 2
    id: code_entered
  - platform: event
    event_type: "zwave_js_notification"
    event_data:
      command_class: 111
      device_id: !input keypad
      event_type: 3
    id: keypad_disarm
  - platform: event
    event_type: "zwave_js_notification"
    event_data:
      command_class: 111
      device_id: !input keypad
      event_type: 5
    id: keypad_arm_away
  - platform: event
    event_type: "zwave_js_notification"
    event_data:
      command_class: 111
      device_id: !input keypad
      event_type: 6
    id: keypad_arm_home
  - platform: event
    event_type: zwave_js_notification
    event_data:
      command_class: 111
      device_id: !input 'keypad'
      event_type: 16
    id: keypad_fire
  - platform: event
    event_type: zwave_js_notification
    event_data:
      command_class: 111
      device_id: !input 'keypad'
      event_type: 17
    id: keypad_police
  - platform: event
    event_type: zwave_js_notification
    event_data:
      command_class: 111
      device_id: !input 'keypad'
      event_type: 19
    id: keypad_medical
  - platform: event
    event_type: "alarmo_failed_to_arm"
    event_data:
      reason: "invalid_code"
    id: invalid_code
  - platform: event
    event_type: "alarmo_failed_to_arm"
    event_data:
      reason: "open_sensors"
    id: need_bypass
  - platform: state
    entity_id: !input alarm
    to: disarmed
    id: alarm_disarmed
  - platform: state
    entity_id: !input alarm
    to: arming
    id: alarm_arming
  - platform: state
    entity_id: !input alarm
    to: armed_away
    id: alarm_armed_away
  - platform: state
    entity_id: !input alarm
    to: armed_home
    id: alarm_armed_home
  - platform: state
    entity_id: !input alarm
    to: pending
    id: alarm_pending
  - platform: state
    entity_id: !input alarm
    to: triggered
    id: alarm_triggered
condition:
  condition: not
  conditions:
    - condition: template
      value_template: "{{ ('from_state' in trigger) and (trigger.from_state.state == 'unknown') }}"
action:
  choose:
    - conditions:
        - condition: trigger
          id:
            - code_entered
            - keypad_disarm
      sequence:
        - service: alarm_control_panel.alarm_disarm
          entity_id: !input alarm
          data:
            code: "{{ trigger.event.data.event_data }}"
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: keypad_arm_away
            - condition: state
              entity_id: !input alarm
              state:
                - "disarmed"
                - "armed_home"
      sequence:
        - choose:
            - conditions:
                condition: template
                value_template: "{{ trigger.event.data.event_data is not none }}"
              sequence:
                - service: alarm_control_panel.alarm_arm_away
                  target:
                    entity_id: !input alarm
                  data:
                    code: "{{ trigger.event.data.event_data }}"
                - service: input_text.set_value
                  target:
                    entity_id: !input pincode
                  data:
                    value: "{{ trigger.event.data.event_data }}"
          default:
            - service: alarm_control_panel.alarm_arm_away
              target:
                entity_id: !input alarm
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: keypad_arm_home
            - condition: state
              entity_id: !input alarm
              state:
                - "disarmed"
      sequence:
        - choose:
            - conditions:
                condition: template
                value_template: "{{ trigger.event.data.event_data is not none }}"
              sequence:
                - service: alarm_control_panel.alarm_arm_home
                  target:
                    entity_id: !input alarm
                  data:
                    code: "{{ trigger.event.data.event_data }}"
                - service: input_text.set_value
                  target:
                    entity_id: !input pincode
                  data:
                    value: "{{ trigger.event.data.event_data }}"
          default:
            - service: alarm_control_panel.alarm_arm_home
              target:
                entity_id: !input alarm
    - conditions:
        - condition: trigger
          id:
            - invalid_code
      sequence:
        - service: zwave_js.set_value
          target:
            device_id: !input keypad
          data:
            command_class: "135"
            endpoint: "0"
            property: "9"
            property_key: "1"
            value: 100
    - conditions:
        - condition: trigger
          id: need_bypass
      sequence:
        - service: zwave_js.set_value
          target:
            device_id: !input keypad
          data:
            command_class: "135"
            endpoint: "0"
            property: "16"
            property_key: "1"
            value: 100
        - wait_for_trigger:
            - platform: event
              event_type: "zwave_js_notification"
              event_data:
                command_class: 111
                device_id: !input keypad
                event_type: 2
          timeout: "5"
          continue_on_timeout: false
        - choose:
            - conditions:
                - condition: state
                  entity_id: alarm_control_panel.alarmo
                  state: armed_home
                  attribute: arm_mode
              sequence:
                - service: alarmo.arm
                  data:
                    entity_id: alarm_control_panel.alarmo
                    mode: home
                    force: true
                    code: "{{ states(_pincode) }}"
            - conditions:
                - condition: state
                  entity_id: alarm_control_panel.alarmo
                  state: armed_away
                  attribute: arm_mode
              sequence:
                - service: alarmo.arm
                  data:
                    entity_id: alarm_control_panel.alarmo
                    mode: away
                    force: true
                    code: "{{ states(_pincode) }}"
          default: []
        - service: input_text.set_value
          target:
            entity_id: !input pincode
          data:
            value: ""
    - conditions:
        - condition: trigger
          id: alarm_disarmed
      sequence:
        - service: zwave_js.set_value
          target:
            device_id: !input keypad
          data:
            command_class: "135"
            endpoint: "0"
            property: "2"
            property_key: "1"
            value: 100
    - conditions:
        - condition: trigger
          id: alarm_armed_away
      sequence:
        - service: zwave_js.set_value
          target:
            device_id: !input keypad
          data:
            command_class: "135"
            endpoint: "0"
            property: "11"
            property_key: "1"
            value: 100
    - conditions:
        - condition: trigger
          id: alarm_armed_home
      sequence:
        - service: zwave_js.set_value
          target:
            device_id: !input keypad
          data:
            command_class: "135"
            endpoint: "0"
            property: "10"
            property_key: "1"
            value: 100
    - conditions:
        - condition: trigger
          id: alarm_arming
      sequence:
        - service: zwave_js.set_value
          target:
            device_id: !input keypad
          data:
            command_class: "135"
            endpoint: "0"
            property: "18"
            property_key: "7"
            value: "{{ state_attr(alarm, 'delay') }}"
    - conditions:
        - condition: trigger
          id: alarm_pending
      sequence:
        - service: zwave_js.set_value
          target:
            device_id: !input keypad
          data:
            command_class: "135"
            endpoint: "0"
            property: "17"
            property_key: "7"
            value: "{{ state_attr(alarm, 'delay') }}"
    - conditions:
        - condition: trigger
          id: alarm_triggered
      sequence:
        - service: zwave_js.set_value
          target:
            device_id: !input keypad
          data:
            command_class: "135"
            endpoint: "0"
            property: "13"
            property_key: "1"
            value: 100
    - conditions:
      - condition: trigger
        id: keypad_fire
      sequence: !input selected_action_fire
    - conditions:
      - condition: trigger
        id: keypad_police
      sequence: !input selected_action_police
    - conditions:
      - condition: trigger
        id: keypad_medical
      sequence: !input selected_action_medical
